name: Deploy OpenStreetMap Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Terraform code
        uses: actions/checkout@v2

      - name: Checkout Application code
        uses: actions/checkout@v2
        with:
          repository: your-username/your-application-repo
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: application

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        working-directory: ./application

      - name: Package application
        run: zip -r my-application.zip .
        working-directory: ./application

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Upload zip to S3
        run: aws s3 cp application/my-application.zip s3://openstreetmap-static-assets/

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      #- name: Terraform Apply
      # run: terraform apply -auto-approve
